### ISSUE TITLE
Ontology files can use a format update

### ISSUE THREAD

**Issue by kwalcock** [WorldModelers/Ontologies#146]

**Comment by kwalcock** [comment]
Justification and suggestions will follow in not too long.

**Comment by kwalcock** [comment]
The need to update the format was discussed a couple of months ago.  Some of the justifications were
* An ontology editor was being added to Causemos and the present format does/did not work well for that task (IIRC).
* We need/want to support [metatdata on non-leaf nodes](https://github.com/WorldModelers/Ontologies/issues/46).  Eidos has a branch in which this is implemented, but in a way that changes the ontology format in the smallest possible way, which isn't very clean.
* The present version is somewhat difficult to work with in that the keys are not fixed.  Some of them are the actual names of nodes and don't come from a small, fixed list.  They might rather be the values.  In this example, anything in front of a colon should come from a fixed set:
```yaml
  - livestock_production_inputs:
    - OntologyNode:
       examples:
       - livestock feed
       name: livestock_feed
```
* The minimal indentation makes working with long files a little difficult, like when browsing the file on github.

The format was [discussed at UAz](https://github.com/clulab/eidos/issues/972) and our top choice looked like this:
```yaml
- node:
    name: wm
    examples:
        - crime
    definition:
    polarity: -1
    semantic type: event
    children: 
        - node:
            name: concept
            examples:
                - crime
            definition:
```
* Nodes are all called `node` and names have been moved to the `name` field.
* Children are explicitly listed under the `children` key.
* Indentation has been increased to four spaces where before it was two and sometimes even zero.
* Non-leaf nodes look just like the others except that they have no children.

**Comment by kwalcock** [comment]
At a recent meeting we discussed these points which are related to the ontology format:

* We could add examples/definitions for specific compositions
  * Some compositions have more meaning than the individual parts
  * Currently no way to structurally add to the ontology - may need separate place to put these
  * Would also need support at the level of reading/grounding

The format might account for adding information to specific compositions.

**Comment by bgyori** [comment]
I think the new proposed format should work well!

**Comment by johnhungerford** [comment]
The proposed format looks good to me. Is there any reason why nodes are structured in a list rather than a dict? Is there an imaginable case of multiple nodes in the same branch having the same name? Why not:

```
wm:
    examples:
        - crime
    definition:
    polarity: -1
    semantic type: event
    children: 
        concept:
            examples:
                - crime
            definition:
```

Just curious -- lists are fine with me.
