### ISSUE TITLE
Root element in new ontology metadata format not a list

### ISSUE THREAD

**Issue by bgyori** [WorldModelers/Ontologies#151]
I realized something I want to clarify with respect to the new format. In https://raw.githubusercontent.com/WorldModelers/Ontologies/master/CompositionalOntology.yml, the root element is a list signified by the `-` before `wm`:
```
- wm:
  - concept:
    - agriculture:
...
```
However, in https://raw.githubusercontent.com/WorldModelers/Ontologies/master/CompositionalOntology_metadata.yml, the root element is not a list:
```
node:
    name: wm
    children:
        - node:
            name: concept
```

This causes complications with a corner case on our end where we have to support ontology extensions that can in principle fall outside the `wm` subtree of the ontology. Should we consider making it the following?
```
- node:
      name: wm
      children:
          - node:
              name: concept
```

**Comment by MihaiSurdeanu** [comment]
Good point.
But don't we need just the children to be a list? 
That is, the root is a single node, which may have a list of children. Just like in any tree data structure.
@kwalcock ?

**Comment by kwalcock** [comment]
It sounds like Ben wants to do

```yaml
- node:
    name: wm
    children:
    ....
- node: # Special things for INDRA
    name: non-wm
    children:
```

I have been wondering who is using the versions without the metadata, the ones with a - still in the top level.  @bgyori, do you need just that metadataless one (that you linked to as an example) to stay a list or do you need both that and the metadata file to have a list, or do they just need to be consistent, etc.?  Having the top level list will probably make a slight exception in other code, and I will double check that it isn't too onerous.  I also haven't checked the program that strips the metadata.
